version: '3.9'
services:
  postgres-server:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'chat_bot'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
  app_1:
    depends_on:
      - postgres-server
    image: 'chatbotservice:latest'
    container_name: app_1
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chat_bot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  app_2:
    depends_on:
      - postgres-server
    image: 'chatbotservice:latest'
    container_name: app_2
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chat_bot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop